services:
  - type: web
    name: video-downloader-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_URL
        value: https://your-api-domain.onrender.com 